package com.schoolbus.controller;
import com.schoolbus.dto.request.TeacherRequest; import com.schoolbus.dto.response.*; import com.schoolbus.entity.*; import com.schoolbus.entity.enums.RoleType; import com.schoolbus.exception.*; import com.schoolbus.repository.*; import com.schoolbus.util.SecurityUtils; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/admin/teachers") @RequiredArgsConstructor public class AdminTeacherController {
 private final TeacherRepository teachers; private final UserRepository users; private final RoleRepository roles; private final SchoolRepository schools; private final PasswordEncoder encoder;
 @GetMapping @Transactional(readOnly=true) public ApiResponse<PageResponse<TeacherResponse>> list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.success(PageResponse.from(teachers.findBySchoolId(sid(),PageRequest.of(page,size)).map(TeacherResponse::from)));}
 @PostMapping @Transactional public ResponseEntity<ApiResponse<TeacherResponse>> create(@Valid @RequestBody TeacherRequest r){if(users.existsByUsername(r.username())||users.existsByEmail(r.email()))throw new BadRequestException("Username or email already exists");User u=new User();copy(u,r);u.setSchool(schools.getReferenceById(sid()));u.setPasswordHash(encoder.encode(r.password()==null||r.password().isBlank()?"Password@123":r.password()));u.getRoles().add(roles.findByName(RoleType.TEACHER).orElseThrow(()->new ResourceNotFoundException("Teacher role not found")));users.save(u);Teacher t=new Teacher();t.setUser(u);t.setSchool(schools.getReferenceById(sid()));copy(t,r);return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success("Teacher created",TeacherResponse.from(teachers.save(t))));}
 @PutMapping("/{id}") @Transactional public ApiResponse<TeacherResponse> update(@PathVariable Long id,@Valid @RequestBody TeacherRequest r){Teacher t=get(id);copy(t.getUser(),r);copy(t,r);return ApiResponse.success(TeacherResponse.from(t));}
 @PatchMapping("/{id}/deactivate") @Transactional public ApiResponse<Void> deactivate(@PathVariable Long id){Teacher t=get(id);t.setActive(false);t.getUser().setActive(false);return ApiResponse.success("Teacher deactivated",null);}
 private Long sid(){return SecurityUtils.getCurrentSchoolId();} private Teacher get(Long id){return teachers.findByIdAndSchoolId(id,sid()).orElseThrow(()->new ResourceNotFoundException("Teacher not found"));}
 private void copy(User u,TeacherRequest r){u.setUsername(r.username());u.setEmail(r.email());u.setFirstName(r.firstName());u.setLastName(r.lastName());u.setPhone(r.phone());if(r.password()!=null&&!r.password().isBlank())u.setPasswordHash(encoder.encode(r.password()));if(r.active()!=null)u.setActive(r.active());}
 private void copy(Teacher t,TeacherRequest r){t.setEmployeeCode(r.employeeCode());t.setDepartment(r.department());t.setSubjects(r.subjects());t.setJoinDate(r.joinDate());t.setPhoneExtension(r.phoneExtension());if(r.active()!=null)t.setActive(r.active());}
}
