-- Seed data. Primary keys are generated by MySQL AUTO_INCREMENT.
-- Password for all seed users: Password@123 (BCrypt).

INSERT INTO roles (name, description) VALUES
    ('ADMIN', 'School administrator with full access'),
    ('DRIVER', 'Bus driver'),
    ('STUDENT', 'Student user'),
    ('PARENT', 'Parent / guardian');

INSERT INTO schools (
    code, name, address, city, state, postal_code, country, phone, email,
    latitude, longitude, timezone, is_active, created_by, updated_by
) VALUES (
    'DEMO001', 'Vidya International School', '123 Education Lane', 'Bengaluru', 'Karnataka',
    '560001', 'India', '+91-80-12345678', 'admin@vidyaschool.edu',
    12.9716000, 77.5946000, 'Asia/Kolkata', TRUE, 'SYSTEM', 'SYSTEM'
);

INSERT INTO users (
    school_id, username, email, password_hash, first_name, last_name, phone,
    is_active, created_by, updated_by
) VALUES
    ((SELECT id FROM schools WHERE code = 'DEMO001'), 'admin', 'admin@vidyaschool.edu',
     '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.G2oQ.YqKxqKxqK',
     'System', 'Admin', '+91-9876543210', TRUE, 'SYSTEM', 'SYSTEM'),
    ((SELECT id FROM schools WHERE code = 'DEMO001'), 'driver1', 'driver1@vidyaschool.edu',
     '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.G2oQ.YqKxqKxqK',
     'Ravi', 'Kumar', '+91-9876543211', TRUE, 'SYSTEM', 'SYSTEM'),
    ((SELECT id FROM schools WHERE code = 'DEMO001'), 'parent1', 'parent1@example.com',
     '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.G2oQ.YqKxqKxqK',
     'Priya', 'Sharma', '+91-9876543212', TRUE, 'SYSTEM', 'SYSTEM');

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u JOIN roles r ON r.name = 'ADMIN' WHERE u.username = 'admin';
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u JOIN roles r ON r.name = 'DRIVER' WHERE u.username = 'driver1';
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u JOIN roles r ON r.name = 'PARENT' WHERE u.username = 'parent1';

INSERT INTO drivers (
    user_id, school_id, license_number, license_expiry, experience_years,
    emergency_contact, is_online, location_enabled, created_by, updated_by
) VALUES (
    (SELECT id FROM users WHERE username = 'driver1'),
    (SELECT id FROM schools WHERE code = 'DEMO001'),
    'KA01-2020-1234567', '2028-12-31', 8, '+91-9876543299', FALSE, FALSE, 'SYSTEM', 'SYSTEM'
);

INSERT INTO parents (
    user_id, school_id, relationship, emergency_contact, created_by, updated_by
) VALUES (
    (SELECT id FROM users WHERE username = 'parent1'),
    (SELECT id FROM schools WHERE code = 'DEMO001'),
    'Mother', '+91-9876543212', 'SYSTEM', 'SYSTEM'
);

INSERT INTO students (
    school_id, parent_id, student_code, first_name, last_name, grade, section, gender,
    pickup_address, pickup_latitude, pickup_longitude, is_active, created_by, updated_by
) VALUES (
    (SELECT id FROM schools WHERE code = 'DEMO001'),
    (SELECT p.id FROM parents p JOIN users u ON u.id = p.user_id WHERE u.username = 'parent1'),
    'STU001', 'Aarav', 'Sharma', '5', 'A', 'MALE',
    '45 Park Street, Bengaluru', 12.9750000, 77.6000000, TRUE, 'SYSTEM', 'SYSTEM'
);

INSERT INTO settings (school_id, setting_key, setting_value, value_type, description, is_public) VALUES
    (NULL, 'app.name', 'School Bus Management', 'STRING', 'Application display name', TRUE),
    (NULL, 'location.update.interval.seconds', '5', 'NUMBER', 'GPS update interval', FALSE),
    (NULL, 'geofence.default.radius.meters', '100', 'NUMBER', 'Default geofence radius', FALSE),
    ((SELECT id FROM schools WHERE code = 'DEMO001'), 'notification.bus.approaching.distance.meters',
     '500', 'NUMBER', 'Distance threshold for approaching notification', FALSE);
