spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false

  flyway:
    schemas: ${DB_SCHEMA:vidya_db}
    default-schema: ${DB_SCHEMA:vidya_db}
    create-schemas: false

logging:
  level:
    root: INFO
    com.schoolbus: INFO
