"use client";
import { useEffect, useState } from "react";
import { useFieldArray, useForm } from "react-hook-form";
import { Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/layout/page-header";
import { DataTable } from "@/components/admin/data-table";
import { EmptyState } from "@/components/admin/empty-state";
import { Dialog } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { routeService } from "@/services/route.service";
import type { Route } from "@/types/route";
type Values = { name: string; code: string; description?: string; distanceKm?: number; estimatedDurationMins?: number; stops: { name: string; address?: string }[] };
export default function RoutesPage() { const [routes, setRoutes] = useState<Route[]>([]), [open, setOpen] = useState(false), [editing, setEditing] = useState<Route | null>(null); const form = useForm<Values>({ defaultValues: { name: "", code: "", stops: [{ name: "" }] } }); const { fields, append, remove } = useFieldArray({ control: form.control, name: "stops" }); const load = () => routeService.list({ size: 100 }).then((x) => setRoutes(x.content)).catch(() => toast.error("Could not load routes")); useEffect(() => { load(); }, []);
const show = (route?: Route) => { setEditing(route ?? null); form.reset(route ? { ...route, stops: route.stops.map(({ name, address }) => ({ name, address })) } : { name: "", code: "", stops: [{ name: "" }] }); setOpen(true); }; const save = async (values: Values) => { try { if (editing) await routeService.update(editing.id, values); else await routeService.create(values); toast.success("Route saved"); setOpen(false); load(); } catch { toast.error("Could not save route"); } };
return <><PageHeader eyebrow="Network" title="Routes" description="Design the stops and travel estimates for every school route." action={<Button onClick={() => show()}><Plus size={17} />Add route</Button>} /><DataTable title={`${routes.length} routes`}><div className="divide-y">{routes.map((route) => <div key={route.id} className="flex items-center justify-between p-5"><div><p className="font-semibold">{route.name} <span className="text-sm font-normal text-[var(--muted-foreground)]">· {route.code}</span></p><p className="mt-1 text-sm text-[var(--muted-foreground)]">{route.stops.length} stops · {route.distanceKm ?? "—"} km · {route.estimatedDurationMins ?? "—"} mins</p></div><Button size="sm" variant="outline" onClick={() => show(route)}>Edit</Button></div>)}</div>{!routes.length && <EmptyState title="No routes yet" action={{ label: "Add route", onClick: () => show() }} />}</DataTable><Dialog open={open} onClose={() => setOpen(false)} title={editing ? "Edit route" : "Add route"}><form onSubmit={form.handleSubmit(save)} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{(["name","code","distanceKm","estimatedDurationMins"] as const).map((n) => <div key={n}><Label>{n === "distanceKm" ? "Distance (km)" : n === "estimatedDurationMins" ? "Duration (mins)" : n[0].toUpperCase() + n.slice(1)}</Label><Input className="mt-1" type={n.includes("Km") || n.includes("Mins") ? "number" : "text"} {...form.register(n)} /></div>)}</div><div><Label>Description</Label><Input className="mt-1" {...form.register("description")} /></div><div><div className="mb-2 flex items-center justify-between"><Label>Stops</Label><Button type="button" size="sm" variant="outline" onClick={() => append({ name: "" })}><Plus size={15} />Stop</Button></div>{fields.map((field, index) => <div key={field.id} className="mb-2 flex gap-2"><Input placeholder={`Stop ${index + 1} name`} {...form.register(`stops.${index}.name`)} /><Input placeholder="Address" {...form.register(`stops.${index}.address`)} /><Button type="button" size="icon" variant="ghost" onClick={() => remove(index)} aria-label="Remove stop"><Trash2 size={16} /></Button></div>)}</div><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit">Save route</Button></div></form></Dialog></>; }
